---
- hosts: webservers 
  become: true
  vars: 
   name: John 
  tasks:
  - name: Install zip
    yum: name=zip state=present
  - name: Copying the files
    copy: src=/home/ansible/test.txt dest=/home/ansible/test.txt
  - name: Display the variables 
    debug:
     msg={{ name }}
- hosts: appservers
  become: true
  vars:  
   name: John 
  tasks:
  - name: Install wget
    yum: name=wget state=present
