---
- hosts: webservers
  become: true
  tags:
   - install-web
  tasks:
  - name: Remove git
    yum: name=git state=absent
    tags:
     - remove_git
  - name: Install zip
    yum: name=zip state=present
    tags:
     - install_zip
  - name: remove wget
    yum: name=wget state=absent
    tags:
      - remove_wget
- hosts: appservers
  become: true
  tags:
   - install-app
  tasks:
  - name: Install httpd
    yum: name=httpd state=present
    tags:
      - install_httpd
  - name: remove maven
    yum: name=maven state=absent
    tags:
     - remove_maven
