---
- hosts: webservers
  become: true
  tasks:
  - name: Install httpd server
    yum: name=httpd state=present
  - name: Start httpd server
    service: name=httpd state=started
  - name: configuration file changes
    copy: src=/home/ansible/index.html dest=/var/www/html/index.html
    notify:
      - restart httpd server
  handlers:
  - name: restart httpd server
    service: name=httpd state=restarted
